# Generated by Django 6.0.1 on 2026-01-22 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kanbanboard',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
