# Generated by Django 6.0.1 on 2026-01-22 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0002_rename_owner_kanbanboard_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kanbanboard',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
