# Generated by Django 6.0.1 on 2026-01-22 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0004_comment_task_comment_task_kanbanboard_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanbanboard',
            name='member_count',
        ),
        migrations.RemoveField(
            model_name='kanbanboard',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='kanbanboard',
            name='tasks_high_prio_count',
        ),
        migrations.RemoveField(
            model_name='kanbanboard',
            name='tasks_to_do_count',
        ),
        migrations.RemoveField(
            model_name='kanbanboard',
            name='ticked_count',
        ),
        migrations.RemoveField(
            model_name='task',
            name='comments',
        ),
    ]
