# Generated by Django 6.0.1 on 2026-01-26 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0005_remove_kanbanboard_member_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
    ]
